name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'helm/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/securecloudshop:latest
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Upload Helm chart as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: helm/securecloudshop
