name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Build Docker image
        run: docker build -t securecloudshop:ci .

      - name: Trivy - Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'securecloudshop:ci'
          format: 'table'
          exit-code: '0'  # do not fail build initially; tighten later
          vuln-type: 'os,library'

      - name: Start app (for ZAP baseline scan)
        run: |
          docker run -d --rm --name scs -p 5000:5000 securecloudshop:ci
          sleep 5

      - name: OWASP ZAP Baseline Scan (DAST) - against running container
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://localhost:5000'
        continue-on-error: true

      - name: Stop app
        if: always()
        run: docker stop scs
